language: objective-c
osx_image: xcode9.1

branches:
  only:
  - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="UnsplashFramework.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="UnsplashFramework iOS"
  - IOS_SDK=iphonesimulator11.1

  matrix:
  - DESTINATION="OS=11.1,name=iPhone X"         SDK="$IOS_SDK" SCHEME="$IOS_FRAMEWORK_SCHEME"  RUN_TESTS="YES"  BUILD_EXAMPLE="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_FRAMEWORK_SCHEME"  RUN_TESTS="YES"  BUILD_EXAMPLE="YES"

script:
  - if [ $RUN_UI_TESTS == "YES" ] && [ $SDK == $IOS_SDK ]; then
      ONLY_ACTIVE_ARCH=YES  test
      xcodebuild clean build -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES test;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'UnsplashFramework'  -cF ios
