language: objective-c
osx_image: xcode9.1

branches:
  only:
  - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="UnsplashFramework.xcodeproj"
  - IOS_SCHEME="UnsplashFramework iOS"
  - IOS_SDK=iphonesimulator11.1

  matrix:
  - DESTINATION="OS=11.1,name=iPhone X"         SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"  RUN_TESTS="YES"  POD_LINT="NO"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"  RUN_TESTS="YES"  POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Debug -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES test;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Debug -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO build;
    fi

  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
