language: objective-c
osx_image: xcode9.1

branches:
  only:
  - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="UnsplashFramework.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="UnsplashFramework iOS"

  matrix:
  - DESTINATION="OS=11.1,name=iPhone X"         SCHEME="$IOS_FRAMEWORK_SCHEME"  RUN_TESTS="YES"  BUILD_EXAMPLE="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  RUN_TESTS="YES"  BUILD_EXAMPLE="YES"
